<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>annotations</Nullable>
    <RootNamespace>LogRotate</RootNamespace>
    <AssemblyName>logrotate</AssemblyName>
    <LangVersion>latest</LangVersion>
    <InvariantGlobalization>false</InvariantGlobalization>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>